//HintName: InheritedParametersTemplate.cs
// This file is generated by Bearded.TD.Generators

using System;
using Bearded.TD.Shared.TechEffects;
using Bearded.Utilities;
using Newtonsoft.Json;

namespace Bearded.TD.Generators.Tests.TechEffects
{
    [ParametersTemplate(typeof(IInheritedParameters))]
    sealed class InheritedParametersTemplate : TemplateBase, IInheritedParameters
    {
        public int LocalParameter { get; }
        public double BaseParameter { get; }

        [JsonConstructor]
        public InheritedParametersTemplate(
            int localParameter,
            double baseParameter)
        {
            LocalParameter = localParameter;
            BaseParameter = baseParameter;
        }

        public bool HasAttributeOfType(AttributeType type) => InheritedParametersModifiable.AttributeIsKnown(type);

        public IInheritedParameters CreateModifiableInstance() => new InheritedParametersModifiable(this);

    }
}
