//HintName: NestedParametersTemplate.cs
// This file is generated by Bearded.TD.Generators

using System;
using Bearded.TD.Shared.TechEffects;
using Bearded.Utilities;
using Newtonsoft.Json;

namespace Bearded.TD.Generators.Tests.TechEffects
{
    [ParametersTemplate(typeof(ContainingType.INestedParameters))]
    sealed class NestedParametersTemplate : TemplateBase, ContainingType.INestedParameters
    {
        public int MyInt { get; }

        [JsonConstructor]
        public NestedParametersTemplate(
            int myInt)
        {
            MyInt = myInt;
        }

        public bool HasAttributeOfType(AttributeType type) => NestedParametersModifiable.AttributeIsKnown(type);

        public ContainingType.INestedParameters CreateModifiableInstance() => new NestedParametersModifiable(this);

    }
}
