# See the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.FluentSourceGen.Tests"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.FluentSourceGen"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD.Generators.Tests"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD.Generators"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD.MasterServer"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD.Proto"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD.Shared"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD.Tests"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "nuget"
    directory: "/src/Bearded.TD"
    schedule:
      interval: "weekly"
      day: "tuesday"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
