using System.Collections.Generic;
using System.Linq;
using Bearded.TD.Generators.Types;

namespace Bearded.TD.Generators;

static partial class SourceTemplates
{
    public static string FileHeader(IEnumerable<string> namespaces, TypeAliases aliases) =>
$"""
{fileTop}
{namespaceUsings(namespaces)}
{typeAliasUsings(aliases)}
""";

    private static string fileTop => "// This file is generated by Bearded.TD.Generators";
    private static string namespaceUsings(IEnumerable<string> namespaces) => Foreach(0, namespaces, n => $"using {n};");

    private static string typeAliasUsings(TypeAliases aliases) =>
        Foreach(
            0,
            aliases.Where(a => a.FullName.Name != a.Alias.Name).OrderBy(a => a.Alias.Name),
            a => a.ToString());
}
