//HintName: ListeningComponent.Events.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Shared.Events;
using FirstEvent = global::Bearded.TD.Generators.Tests.Events.EventImplementationsNamespace.FirstEvent;

namespace Bearded.TD.Generators.Tests.Events;

partial class ListeningComponent :
    IListener<FirstEvent>
{
    protected override void RegisterHandlers()
    {
        Events.Subscribe<FirstEvent>(this);
    }

    protected override void UnregisterHandlers()
    {
        Events.Unsubscribe<FirstEvent>(this);
    }

    public void HandleEvent(FirstEvent e)
    {
        onFirstEvent(e);
    }
}
