//HintName: ComplexCommand_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;
using MyOwnClass = global::Bearded.TD.Generators.Tests.Commands.MyOwnClass;
using MyOwnStruct = global::Bearded.TD.Generators.Tests.Commands.MyOwnStruct;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class ComplexCommand
{
    public static ISerializableCommand<GameInstance> Command(MyOwnClass aClass, MyOwnStruct aStruct, int anInteger, string aString)
        => new Implementation(aClass, aStruct, anInteger, aString);

    private sealed class Implementation(MyOwnClass aClass, MyOwnStruct aStruct, int anInteger, string aString)
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute(aClass, aStruct, anInteger, aString);
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer(aClass, aStruct, anInteger, aString);
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        private MyOwnClass aClass;
        private MyOwnStruct aStruct;
        private int anInteger;
        private string aString;

        public Serializer(MyOwnClass aClass, MyOwnStruct aStruct, int anInteger, string aString) : this()
        {
            this.aClass = aClass;
            this.aStruct = aStruct;
            this.anInteger = anInteger;
            this.aString = aString;
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(aClass, aStruct, anInteger, aString);
        }

        public void Serialize(INetBufferStream stream)
        {
            stream.Serialize(ref aClass);
            stream.Serialize(ref aStruct);
            stream.Serialize(ref anInteger);
            stream.Serialize(ref aString);
        }
    }
}
