//HintName: CommandWithCollidingTypes_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;
using CollidingType = global::Bearded.TD.Generators.Tests.Commands.CommandWithCollidingTypes.CollidingType;
using CollidingType_2 = global::Bearded.TD.Generators.Tests.Commands.CommandWithCollidingTypes.OtherType.CollidingType;
using CollidingType_3 = global::Bearded.TD.Generators.Tests.Commands.CommandWithCollidingTypes.OtherType2.CollidingType;
using CollidingTypeSerializerConverters = global::Bearded.TD.Generators.Tests.Commands.CollidingTypeSerializerConverters;
using CollidingTypeSerializerConverters_2 = global::Bearded.TD.Generators.Tests.Commands.CommandWithCollidingTypes.CollidingTypeSerializerConverters;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class CommandWithCollidingTypes
{
    public static ISerializableCommand<GameInstance> Command(CollidingType one, CollidingType_2 two, CollidingType_3 three)
        => new Implementation(one, two, three);

    private sealed class Implementation(CollidingType one, CollidingType_2 two, CollidingType_3 three)
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute(one, two, three);
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer(one, two, three);
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        private int one;
        private int two;
        private int three;

        public Serializer(CollidingType one, CollidingType_2 two, CollidingType_3 three) : this()
        {
            this.one = CollidingTypeSerializerConverters.SerializeCollidingType.Serialize(one);
            this.two = CollidingTypeSerializerConverters.SerializeOtherTypeCollidingType.Serialize(two);
            this.three = CollidingTypeSerializerConverters_2.SerializeCollidingType.Serialize(three);
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(
                CollidingTypeSerializerConverters.SerializeCollidingType.Deserialize(one, game),
                CollidingTypeSerializerConverters.SerializeOtherTypeCollidingType.Deserialize(two, game),
                CollidingTypeSerializerConverters_2.SerializeCollidingType.Deserialize(three, game)
            );
        }

        public void Serialize(INetBufferStream stream)
        {
            stream.Serialize(ref one);
            stream.Serialize(ref two);
            stream.Serialize(ref three);
        }
    }
}
