//HintName: SimpleCommand_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class SimpleCommand
{
    public static ISerializableCommand<GameInstance> Command(int anInteger, string aString)
        => new Implementation(anInteger, aString);

    private sealed class Implementation(int anInteger, string aString)
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute(anInteger, aString);
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer(anInteger, aString);
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        private int anInteger;
        private string aString;

        public Serializer(int anInteger, string aString) : this()
        {
            this.anInteger = anInteger;
            this.aString = aString;
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(
                anInteger,
                aString
            );
        }

        public void Serialize(INetBufferStream stream)
        {
            stream.Serialize(ref anInteger);
            stream.Serialize(ref aString);
        }
    }
}
