//HintName: CommandWithSerializer_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;
using MyConvertibleDeserializedType = global::Bearded.TD.Generators.Tests.Commands.MyConvertibleDeserializedType;
using MyConvertibleSerializedType = global::Bearded.TD.Generators.Tests.Commands.MyConvertibleSerializedType;
using MySerializedType = global::Bearded.TD.Generators.Tests.Commands.MySerializedType;
using SomeSerializersAndConverters = global::Bearded.TD.Generators.Tests.Commands.SomeSerializersAndConverters;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class CommandWithSerializer
{
    public static ISerializableCommand<GameInstance> Command(MySerializedType myType, MyConvertibleDeserializedType myConvertibleType)
        => new Implementation(myType, myConvertibleType);

    private sealed class Implementation(MySerializedType myType, MyConvertibleDeserializedType myConvertibleType)
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute(myType, myConvertibleType);
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer(myType, myConvertibleType);
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        private MySerializedType myType;
        private MyConvertibleSerializedType myConvertibleType;

        public Serializer(MySerializedType myType, MyConvertibleDeserializedType myConvertibleType) : this()
        {
            this.myType = myType;
            this.myConvertibleType = SomeSerializersAndConverters.Converter.Serialize(myConvertibleType);
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(
                myType,
                SomeSerializersAndConverters.Converter.Deserialize(myConvertibleType, game)
            );
        }

        public void Serialize(INetBufferStream stream)
        {
            SomeSerializersAndConverters.SerializeOnly(stream, ref myType);
            SomeSerializersAndConverters.SerializeConverted(stream, ref myConvertibleType);
        }
    }
}
