//HintName: ComplexCommand_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;
using List_Dictionary_MyOwnClass_MyOwnStruct = global::System.Collections.Generic.List<global::System.Collections.Generic.Dictionary<global::Bearded.TD.Generators.Tests.Commands.MyOwnClass, global::Bearded.TD.Generators.Tests.Commands.MyOwnStruct>>;
using List_MyOwnClass = global::System.Collections.Generic.List<global::Bearded.TD.Generators.Tests.Commands.MyOwnClass>;
using MyOwnClass = global::Bearded.TD.Generators.Tests.Commands.MyOwnClass;
using MyOwnStruct = global::Bearded.TD.Generators.Tests.Commands.MyOwnStruct;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class ComplexCommand
{
    public static ISerializableCommand<GameInstance> Command(MyOwnClass aClass, MyOwnStruct aStruct, List_MyOwnClass aListOfClasses, List_Dictionary_MyOwnClass_MyOwnStruct aListOfDictionaries, int anInteger, string aString)
        => new Implementation(aClass, aStruct, aListOfClasses, aListOfDictionaries, anInteger, aString);

    private sealed class Implementation(MyOwnClass aClass, MyOwnStruct aStruct, List_MyOwnClass aListOfClasses, List_Dictionary_MyOwnClass_MyOwnStruct aListOfDictionaries, int anInteger, string aString)
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute(aClass, aStruct, aListOfClasses, aListOfDictionaries, anInteger, aString);
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer(aClass, aStruct, aListOfClasses, aListOfDictionaries, anInteger, aString);
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        private MyOwnClass aClass;
        private MyOwnStruct aStruct;
        private List_MyOwnClass aListOfClasses;
        private List_Dictionary_MyOwnClass_MyOwnStruct aListOfDictionaries;
        private int anInteger;
        private string aString;

        public Serializer(MyOwnClass aClass, MyOwnStruct aStruct, List_MyOwnClass aListOfClasses, List_Dictionary_MyOwnClass_MyOwnStruct aListOfDictionaries, int anInteger, string aString) : this()
        {
            this.aClass = aClass;
            this.aStruct = aStruct;
            this.aListOfClasses = aListOfClasses;
            this.aListOfDictionaries = aListOfDictionaries;
            this.anInteger = anInteger;
            this.aString = aString;
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(
                aClass,
                aStruct,
                aListOfClasses,
                aListOfDictionaries,
                anInteger,
                aString
            );
        }

        public void Serialize(INetBufferStream stream)
        {
            stream.Serialize(ref aClass);
            stream.Serialize(ref aStruct);
            stream.Serialize(ref aListOfClasses);
            stream.Serialize(ref aListOfDictionaries);
            stream.Serialize(ref anInteger);
            stream.Serialize(ref aString);
        }
    }
}
