//HintName: CommandWithConverter_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;
using MyType = global::Bearded.TD.Generators.Tests.Commands.MyType;
using SerializerConverters = global::Bearded.TD.Generators.Tests.Commands.SerializerConverters;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class CommandWithConverter
{
    public static ISerializableCommand<GameInstance> Command(MyType myType)
        => new Implementation(myType);

    private sealed class Implementation(MyType myType)
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute(myType);
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer(myType);
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        private int myType;

        public Serializer(MyType myType) : this()
        {
            this.myType = SerializerConverters.SerializeMyType.Serialize(myType);
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(
                SerializerConverters.SerializeMyType.Deserialize(myType, game)
            );
        }

        public void Serialize(INetBufferStream stream)
        {
            stream.Serialize(ref myType);
        }
    }
}
