//HintName: EmptyCommand_Implementation.g.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Commands;
using Bearded.TD.Commands.Serialization;
using Bearded.TD.Networking.Serialization;
using Bearded.TD.Utilities;
using Bearded.Utilities;
using Bearded.Utilities.SpaceTime;

namespace Bearded.TD.Generators.Tests.Commands;

static partial class EmptyCommand
{
    public static ISerializableCommand<GameInstance> Command()
        => new Implementation();

    private sealed class Implementation()
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute();
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer();
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        public Serializer() : this()
        {
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(

            );
        }

        public void Serialize(INetBufferStream stream)
        {
        }
    }
}
