using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Bearded.TD.Generators.Serializers;

public partial class CommandGenerator
{
    private const string serializerContextTypeName = "global::Bearded.TD.Game.GameInstance";

    private const string serializerContextSerializeMethodName = "Serialize";
    private const string serializerContextDeserializeMethodName = "Deserialize";

    private static readonly ImmutableArray<string> defaultNameSpaces = ImmutableArray.Create<string>(
        "Bearded.TD.Commands",
        "Bearded.TD.Commands.Serialization",
        "Bearded.TD.Networking.Serialization",
        "Bearded.TD.Utilities",
        "Bearded.Utilities",
        "Bearded.Utilities.SpaceTime"
    );

    private record struct SerializerConverterInfo(
        string ConverterName, UsedType DeserializedType, UsedType SerializedType);

    private record struct CommandInfo(
        string Namespace,
        string ClassName,
        EquatableArray<Parameter> Parameters
    );

    private record struct Parameter(string Name, UsedType Type);

    private record struct UsedType(string ShortName, string FullName);

    private static void execute(SourceProductionContext context, CommandInfo? commandInfo)
    {
        if (commandInfo is not { } info)
            return;

        var parametersList = string.Join(", ", info.Parameters.Select(p => p.Name));
        var argumentList = string.Join(", ", info.Parameters.Select(p => $"{p.Type.ShortName} {p.Name}"));

        var usedTypes = info.Parameters.Select(p => p.Type).ToList();

        var source =
$$"""
// This file is generated by Bearded.TD.Generators
{{@foreach(0, defaultNameSpaces, n => $"using {n};")}}
{{
    @foreach(0,
        usedTypes.Where(p => p.ShortName != p.FullName),
        p => $"using {p.ShortName} = {p.FullName};"
    )
}}

namespace {{info.Namespace}};

static partial class {{info.ClassName}}
{
    public static ISerializableCommand<GameInstance> Command({{argumentList}})
        => new Implementation({{parametersList}});

    private sealed class Implementation({{argumentList}})
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute({{parametersList}});
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer({{parametersList}});
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        {{foreachParam(2, p => $"private {p.Type.ShortName} {p.Name};")}}

        public Serializer({{argumentList}}) : this()
        {
            {{foreachParam(3, p => $"this.{p.Name} = {p.Name};")}}
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation({{parametersList}});
        }

        public void Serialize(INetBufferStream stream)
        {
            {{foreachParam(3, p => $"stream.Serialize(ref {p.Name});")}}
        }
    }
}
""";

        source = cleanWhiteSpace(source);

        context.AddSource($"{info.ClassName}_Implementation.g.cs", source);

        return;

        string foreachParam(int indents, Func<Parameter, string> template, string separator = "\n")
        {
            return @foreach(indents, info.Parameters, template, separator);
        }

        static string @foreach<T>(int indents, IEnumerable<T> values, Func<T, string> template, string separator = "\n")
        {
            return string.Join($"{separator}{indent(indents)}", values.Select(template));
        }

        static string indent(int i) => new(' ', i * 4);
    }

    private static string cleanWhiteSpace(string source)
    {
        // strip trailing whitespace
        source = Regex.Replace(source, @"[ \t]+(\r?\n)", "$1");

        // remove multiple consecutive empty lines
        source = Regex.Replace(source, @"(\r?\n){3,}", "$1$1");

        // remove empty lines after { or ]
        source = Regex.Replace(source, @"([\{\]])(\r?\n){2}", "$1$2");

        return source;
    }
}
