using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Bearded.TD.Generators.Types;
using Microsoft.CodeAnalysis;
using static Bearded.TD.Generators.SourceTemplates;

namespace Bearded.TD.Generators.Serializers;

public partial class CommandGenerator
{
    private const string serializerContextTypeName = "global::Bearded.TD.Game.GameInstance";

    private const string serializerContextSerializeMethodName = "Serialize";
    private const string serializerContextDeserializeMethodName = "Deserialize";

    private static readonly ImmutableArray<string> defaultNameSpaces = ImmutableArray.Create<string>(
        "Bearded.TD.Commands",
        "Bearded.TD.Commands.Serialization",
        "Bearded.TD.Networking.Serialization",
        "Bearded.TD.Utilities",
        "Bearded.Utilities",
        "Bearded.Utilities.SpaceTime"
    );

    private record struct CommandInfoWithConverters(
        CommandInfo Command,
        EquatableArray<SerializerConverterInfo> Converters
    );

    private record struct SerializerConverterInfo(
        TypeName ConverterType, string ConverterMemberName, TypeName DeserializedType, TypeName SerializedType);

    private record struct CommandInfo(
        string Namespace,
        string ClassName,
        EquatableArray<Parameter> Parameters
    );

    private record struct Parameter(string Name, TypeName Type);

    private static void execute(
        SourceProductionContext context,
        CommandInfoWithConverters info)
    {
        var (command, converters) = info;

        var aliases = new TypeAliases();

        aliases.AddRange(command.Parameters.Select(p => p.Type));
        aliases.AddRange(converters.Select(c => c.ConverterType));
        aliases.AddRange(converters.Select(c => c.SerializedType));

        var parametersList = string.Join(", ", command.Parameters.Select(p => p.Name));
        var argumentList = string.Join(", ", command.Parameters.Select(p => $"{aliases[p.Type]} {p.Name}"));

        var source =
$$"""
// This file is generated by Bearded.TD.Generators
{{Foreach(0, defaultNameSpaces, n => $"using {n};")}}
{{Foreach(0, aliases.Where(a => a.FullName.Name != a.Alias.Name).OrderBy(a => a.Alias), a => a.ToString())}}

namespace {{command.Namespace}};

static partial class {{command.ClassName}}
{
    public static ISerializableCommand<GameInstance> Command({{argumentList}})
        => new Implementation({{parametersList}});

    private sealed class Implementation({{argumentList}})
        : ISerializableCommand<GameInstance>
    {
        public void Execute()
        {
            execute({{parametersList}});
        }

        public ICommandSerializer<GameInstance> Serializer
            => new Serializer({{parametersList}});
    }

    private sealed class Serializer() : ICommandSerializer<GameInstance>
    {
        {{foreachParam(2, p => $"private {serializedTypeName(p)} {p.Name};")}}

        public Serializer({{argumentList}}) : this()
        {
            {{foreachParam(3, p => $"this.{p.Name} = {serialize(p)};")}}
        }

        public ISerializableCommand<GameInstance> GetCommand(GameInstance game)
        {
            return new Implementation(
                {{foreachParam(4, deserialize, ",\n")}}
            );
        }

        public void Serialize(INetBufferStream stream)
        {
            {{foreachParam(3, p => $"stream.Serialize(ref {p.Name});")}}
        }
    }
}
""";

        source = CleanWhiteSpace(source);

        context.AddSource($"{command.ClassName}_Implementation.g.cs", source);

        return;

        ShortTypeName serializedTypeName(Parameter parameter)
        {
            foreach (var converter in converters)
            {
                if (converter.DeserializedType.FullName == parameter.Type.FullName)
                {
                    return aliases[converter.SerializedType];
                }
            }

            return aliases[parameter.Type];
        }

        string serialize(Parameter parameter)
        {
            foreach (var converter in converters)
            {
                if (converter.DeserializedType.FullName == parameter.Type.FullName)
                {
                    return
                        aliases[converter.ConverterType] +
                        $".{converter.ConverterMemberName}" +
                        $".{serializerContextSerializeMethodName}({parameter.Name})";
                }
            }

            return $"{parameter.Name}";
        }

        string deserialize(Parameter parameter)
        {
            foreach (var converter in converters)
            {
                if (converter.DeserializedType.FullName == parameter.Type.FullName)
                {
                    return
                        aliases[converter.ConverterType] +
                        $".{converter.ConverterMemberName}" +
                        $".{serializerContextDeserializeMethodName}({parameter.Name}, game)";
                }
            }

            return $"{parameter.Name}";
        }

        string foreachParam(int indents, Func<Parameter, string> template, string separator = "\n")
        {
            return Foreach(indents, command.Parameters, template, separator);
        }
    }
}
