using Bearded.TD.Generators.Types;
using Bearded.TD.Shared.Events;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using static Bearded.TD.Generators.SourceTemplates;

namespace Bearded.TD.Generators.Events;

[Generator]
public partial class EventHandlerGenerator : IIncrementalGenerator
{
    private const string eventBaseTypeName =
        "global::Bearded.TD.Game.Simulation.GameObjects.IComponentEvent";
    private static readonly ImmutableArray<string> defaultNamespaces =
        ImmutableArray.Create(
            "Bearded.TD.Shared.Events"
        );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerMethods =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                typeof(HandlerAttribute).FullName!,
                predicate: static (node, _) => isValidHandlerMethod(node),
                transform: static (ctx, _) => handlerMethodFromContext(ctx))
            .WhereNotNull()
            // TODO: combine methods from the same class
            .Select((m, _) => new ClassWithHandlers(m.ComponentType, "", ImmutableArray.Create(m)));

        context.RegisterSourceOutput(handlerMethods, generateSource);
    }

    private static bool isValidHandlerMethod(SyntaxNode node)
    {
        // Check the method
        if (node is not MethodDeclarationSyntax method ||
            method.ParameterList.Parameters.Count != 1)
        {
            return false;
        }

        // Check the parent class
        if (method.Parent is not ClassDeclarationSyntax { Modifiers: var mods } ||
            !mods.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)))
        {
            return false;
        }

        return true;
    }

    private static HandlerMethod? handlerMethodFromContext(GeneratorAttributeSyntaxContext context)
    {
        var method = (IMethodSymbol) context.TargetSymbol;
        var semanticModel = context.SemanticModel;

        var methodName = method.Name;
        var eventParameter = method.Parameters[0];
        if (!eventParameter.Type.AllInterfaces
            .Select(TypeName.From)
            .Any(name => name.FullName.Name == eventBaseTypeName))
        {
            return null;
        }
        var eventType = TypeName.From(eventParameter.Type);

        if (semanticModel.GetDeclaredSymbol(context.TargetNode.Parent!) is not ITypeSymbol parentClass)
        {
            return null;
        }
        var componentType = TypeName.From(parentClass);

        return new HandlerMethod(componentType, methodName, eventType);
    }

    private static void generateSource(
        SourceProductionContext context, ClassWithHandlers classWithHandlers)
    {
        var methods = classWithHandlers.Handlers;

        var aliases = new TypeAliases();
        aliases.AddRange(methods.Select(m => m.EventType));

        // TODO: add newlines
        var listenerList =
            string.Join(", ", methods.Select(m => $"IListener<{aliases[m.EventType]}>"));

        var source =
$$"""
// This file is generated by Bearded.TD.Generators
{{Foreach(0, defaultNamespaces, n => $"using {n};")}}
{{Foreach(0, aliases.Where(a => a.FullName.Name != a.Alias.Name).OrderBy(a => a.Alias.Name), a => a.ToString())}}

namespace {{classWithHandlers.Namespace}};

partial class {{classWithHandlers.Name}} : {{listenerList}}
{
    protected override RegisterHandlers()
    {
        {{Foreach(2, methods, subscribe)}}
    }

    protected override UnregisterHandlers()
    {
        {{Foreach(2, methods, unsubscribe)}}
    }

    {{Foreach(0, methods, handleEvent)}}
}
""";

        source = CleanWhiteSpace(source);

        context.AddSource($"{classWithHandlers.Name}.Events.g.cs", source);

        return;

        string subscribe(HandlerMethod method)
        {
            return $"Events.Subscribe<{aliases[method.EventType]}>(this);";
        }

        string unsubscribe(HandlerMethod method)
        {
            return $"Events.Unsubscribe<{aliases[method.EventType]}>(this);";
        }

        string handleEvent(HandlerMethod method)
        {
            return
$$"""
    public void HandleEvent({{aliases[method.EventType]}} e)
    {
        {{method.MethodName}}(e);
    }
""";
        }
    }

    private record struct ClassWithHandlers(
        TypeName Name,
        string Namespace,
        ImmutableArray<HandlerMethod> Handlers);

    private record struct HandlerMethod(
        TypeName ComponentType, string MethodName, TypeName EventType);
}
