//HintName: MyEventListener.cs
// This file is generated by Bearded.TD.Generators
using Bearded.TD.Generators.Tests.Listeners.EventImplementationsNamespace;
using Bearded.TD.Generators.Tests.Listeners.GameEventsNamespace;

namespace Bearded.TD.Generators.Tests.Listeners.ListenerNamespace
{
    sealed partial class MyEventListener
    {
        private void subscribeAllEvents(MyEvents events)
        {
            events.Subscribe<FirstEvent>(this);
            events.Subscribe<SecondEvent>(this);
            events.Subscribe<PreviewEvent>(this);
        }

        private void unsubscribeAllEvents(MyEvents events)
        {
            events.Unsubscribe<FirstEvent>(this);
            events.Unsubscribe<SecondEvent>(this);
            events.Unsubscribe<PreviewEvent>(this);
        }

    }
}
