name: Run tests

on:
  workflow_call

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up dotnet
        uses: ./.github/actions/setup-environment

      - name: Install dependencies
        run: dotnet restore
        shell: bash
      - name: Build
        run: dotnet build -c Release --no-restore
        shell: bash

      - name: Test Bearded.TD
        run: dotnet test src/Bearded.TD.Tests -c Release --no-build --logger "trx;LogFileName=test-results-td.trx"
        shell: bash
      - name: Test Bearded.TD.Generators
        run: dotnet test src/Bearded.TD.Generators.Tests -c Release --no-build --logger "trx;LogFileName=test-results-gen.trx"
        shell: bash

      - name: Upload Verify test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: verify-test-results
          path: |
            **/*.received.*
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/test-results-*.trx
