name: Build & test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: 0 1 * * WED

jobs:
  build:

    strategy:
      matrix:
        dotnet_version: [6.0.x, '6.0.201']

    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet_version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --logger "trx;LogFileName=test-results-$ {{ matrix.dotnet_version }}.trx"
      - name: Upload Verify test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: verify-test-results
          path: |
            **/*.received.*
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/test-results*.trx
