name: Increment version

on:
  workflow_dispatch:
    inputs:
      branch:
        required: false
        default: 'develop'
        type: string
  workflow_call:
    inputs:
      branch:
        required: false
        default: 'develop'
        type: string

jobs:

  update_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Increment version number
        id: increment-version
        run: |
          MINOR=$(grep 'BaseVersionString =' src/Bearded.TD/Config.cs | sed -nr 's/.*[0-9]+\.([0-9]+).*/\1/p')
          NEW_MINOR=$(($MINOR + 1))
          sed -r "s/(.*)(BaseVersionString = \"[0-9]+.)([0-9]+)(.*)/\1\2$NEW_MINOR\4/" src/Bearded.TD/Config.cs
          echo "new_version=0.$NEW_MINOR" >> "$GITHUB_OUTPUT"

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'src/Bearded.TD/Config.cs'
          message: '⬆️ Increment version to ${{ steps.increment-version.outputs.new_version }}'
          push: ${{ inputs.branch }}
